### DISCUSSION TITLE
TLS verification skip in server level, not application

### DISCUSSION THREAD

**Discussion by Boniker** [valkey-io/valkey#1752] [Q&A]
Hello everyone, 

We have `valkey` running in `k8s`. It's currently using `tcp` connection, but we want to change it to a `tls` connection.

We have several clients (`java`, `php`, `nodejs` applications) that don't have self-signed certificates generated to connect to `valkey`.
At the same time we also don't want to add the following code snippet everywhere, like (`--insecure`)
```
  ...(config.redis.scheme === 'tls' && {
    tls: {
      rejectUnauthorized: false
    }
  }),
```

_Valkey_ config file (chart bitnami):
```
  values:
    tls:
      enabled: false
      autoGenerated: true
      authClients: false
    commonConfiguration: |-
      tls-auth-clients no
```

The question: is it possible to allow/enable skip ca verify in the `valkey` server totally, but not in per clients (applications)?
